services:
  server:
    container_name: central-controle-server
    build:
      context: ./server
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  web:
    container_name: central-controle-web
    build:
      context: ./web
    depends_on:
      - server

  nginx:
    container_name: central-controle-nginx
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - web