services:
  server:
    container_name: central-controle-server
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=${DB_URL}
      - DATASOURCE_USERNAME=${DB_USERNAME}
      - DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

  web:
    container_name: central-controle-web
    build:
      context: ./web
    ports:
      - "5173:5173"
    depends_on:
      - server

  nginx:
    container_name: central-controle-nginx
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - web