version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"

  web:
    build:
      context: ./web
    ports:
      - "5173:5173"
    depends_on:
      - server