services:
  server:
    container_name: ServerCentralControle
    build:
      context: ./server
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - TIME_ZONE=${TIME_ZONE}
      - DATE_FORMAT=${DATE_FORMAT}
      - SCHEMA=${SCHEMA}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    container_name: WebCentralControle
    build:
      context: ./web
    depends_on:
      - server

  nginx:
    container_name: NginxCentralControle
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - web